# Generated by Django 5.1.2 on 2024-10-31 14:26

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(blank=True, default='none', max_length=40, upload_to=profiles.models.user_directory_path, verbose_name='File'),
        ),
    ]
